# Generated by Django 5.1.7 on 2025-05-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingCourseInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('house_no', models.CharField(max_length=50)),
                ('purok', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('town_municipality', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('birthplace', models.CharField(max_length=100)),
                ('lto_client_id', models.CharField(max_length=50)),
                ('preferred_schedule', models.CharField(blank=True, max_length=100)),
                ('course_type', models.CharField(max_length=100)),
                ('signature', models.FileField(upload_to='signatures/')),
            ],
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
